"""Native CLI runner helpers for Codex."""

from __future__ import annotations

import asyncio
import base64
import contextlib
import json
import os
import re
import shlex
import shutil
import time
import typing
import uuid
from pathlib import Path

from langbot_plugin.api.agent_tools import (
    AgentMCPServerConfig,
    AgentRunExternalTools,
    AgentRunMCPAccess,
    AgentRuntimeDaemonClient,
    AgentRuntimeDaemonError,
    agent_runtime_daemon_config_from_plugin_config,
    get_agent_runtime_daemon_hub,
)
from langbot_plugin.api.definition.components.agent_runner.runner import AgentRunner
from langbot_plugin.api.entities.builtin.agent_runner import AgentRunContext, AgentRunResult

SESSION_STATE_KEY = "external.codex_session_id"
SUPPORTED_LOCATIONS = {"local", "remote-ssh", "daemon"}


class NativeCliError(Exception):
    def __init__(self, message: str, *, code: str = "codex.error", retryable: bool = False) -> None:
        super().__init__(message)
        self.message = message
        self.code = code
        self.retryable = retryable


def _to_bool(value: typing.Any, default: bool = False) -> bool:
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return bool(value)
    if isinstance(value, str):
        return value.strip().lower() in {"1", "true", "yes", "y", "on"}
    return bool(value)


def _to_float(value: typing.Any, default: float) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def _to_int(value: typing.Any, default: int) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def _parse_args(value: typing.Any) -> list[str]:
    if value is None:
        return []
    if isinstance(value, list):
        return [str(item) for item in value if str(item)]
    text = str(value).strip()
    return shlex.split(text) if text else []


def _parse_json_object(value: typing.Any, *, label: str) -> dict[str, typing.Any]:
    if value in (None, ""):
        return {}
    if isinstance(value, dict):
        return dict(value)
    try:
        parsed = json.loads(str(value))
    except json.JSONDecodeError as exc:
        raise NativeCliError(f"{label} must be a JSON object", code="codex.config_invalid") from exc
    if not isinstance(parsed, dict):
        raise NativeCliError(f"{label} must be a JSON object", code="codex.config_invalid")
    return parsed


def _parse_json_list(value: typing.Any, *, label: str) -> list[typing.Any]:
    if value in (None, ""):
        return []
    if isinstance(value, list):
        return list(value)
    try:
        parsed = json.loads(str(value))
    except json.JSONDecodeError as exc:
        raise NativeCliError(f"{label} must be a JSON array", code="codex.config_invalid") from exc
    if not isinstance(parsed, list):
        raise NativeCliError(f"{label} must be a JSON array", code="codex.config_invalid")
    return parsed


def _parse_config_args(value: typing.Any) -> list[str]:
    if isinstance(value, str) and value.strip().startswith("["):
        return [str(item) for item in _parse_json_list(value, label="args-json")]
    if isinstance(value, list):
        return [str(item) for item in value]
    return _parse_args(value)


def _mcp_server_to_config(server: AgentMCPServerConfig) -> dict[str, typing.Any]:
    if server.transport == "http":
        return {
            "type": "http",
            "url": server.url,
            "headers": dict(server.headers),
        }
    return {
        "command": server.command,
        "args": list(server.args),
        "env": dict(server.env),
    }


def _mcp_servers_config(servers: list[AgentMCPServerConfig], extra_servers: list[typing.Any]) -> dict[str, typing.Any]:
    mcp_servers: dict[str, typing.Any] = {}
    for server in servers:
        mcp_servers[server.name] = _mcp_server_to_config(server)
    for item in extra_servers:
        if isinstance(item, dict) and item.get("name"):
            server_name = str(item["name"])
            server_config = dict(item)
            server_config.pop("name", None)
            mcp_servers[server_name] = server_config
    return mcp_servers


_BARE_TOML_KEY_RE = re.compile(r"^[A-Za-z0-9_-]+$")
_MANAGED_MCP_BEGIN = "# BEGIN langbot-managed mcp_servers (do not edit; regenerated by codex-agent)"
_MANAGED_MCP_END = "# END langbot-managed mcp_servers"


def _toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _toml_key(value: str) -> str:
    return value if _BARE_TOML_KEY_RE.match(value) else _toml_string(value)


def _toml_value(value: typing.Any) -> str:
    if value is None:
        raise NativeCliError("mcp server config cannot contain null values", code="codex.config_invalid")
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        return _toml_string(value)
    if isinstance(value, list):
        return "[" + ", ".join(_toml_value(item) for item in value) + "]"
    if isinstance(value, dict):
        parts = [f"{_toml_key(str(key))} = {_toml_value(value[key])}" for key in sorted(value)]
        return "{ " + ", ".join(parts) + " }"
    raise NativeCliError(f"unsupported mcp config value type: {type(value).__name__}", code="codex.config_invalid")


def _mcp_config_toml(mcp_servers: dict[str, typing.Any]) -> str:
    if not mcp_servers:
        return ""
    lines = [_MANAGED_MCP_BEGIN]
    for index, name in enumerate(sorted(mcp_servers)):
        if index:
            lines.append("")
        if not _BARE_TOML_KEY_RE.match(name):
            raise NativeCliError(
                f"mcp server name {name!r} must contain only ASCII letters, digits, '_' or '-'",
                code="codex.config_invalid",
            )
        server = mcp_servers[name]
        if not isinstance(server, dict):
            raise NativeCliError(f"mcp server {name!r} must be a JSON object", code="codex.config_invalid")
        lines.append(f"[mcp_servers.{name}]")
        for key in sorted(server):
            lines.append(f"{_toml_key(str(key))} = {_toml_value(server[key])}")
    lines.append(_MANAGED_MCP_END)
    return "\n".join(lines) + "\n"


def _safe_home_name(value: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_.-]+", "-", value).strip(".-")
    return safe[:96] or f"run-{uuid.uuid4()}"


def _shared_codex_home(env: dict[str, str]) -> Path:
    configured = env.get("CODEX_HOME") or os.environ.get("CODEX_HOME")
    if configured:
        return Path(configured).expanduser()
    return Path.home() / ".codex"


def _symlink_or_copy_file(src: Path, dst: Path) -> None:
    if not src.exists():
        return
    if dst.exists() or dst.is_symlink():
        dst.unlink()
    try:
        dst.symlink_to(src)
    except OSError:
        shutil.copy2(src, dst)


def _symlink_dir(src: Path, dst: Path) -> None:
    src.mkdir(parents=True, exist_ok=True)
    if dst.exists() or dst.is_symlink():
        if dst.is_symlink():
            dst.unlink()
        return
    try:
        dst.symlink_to(src, target_is_directory=True)
    except OSError:
        dst.mkdir(parents=True, exist_ok=True)


def _prepare_local_codex_home(
    workspace: str,
    home_key: str,
    env: dict[str, str],
    mcp_toml: str,
) -> tuple[dict[str, str], str]:
    workspace_path = Path(workspace).expanduser().resolve()
    workspace_path.mkdir(parents=True, exist_ok=True)
    home = workspace_path / ".langbot-codex-home" / _safe_home_name(home_key)
    if home.exists() or home.is_symlink():
        shutil.rmtree(home)
    home.mkdir(parents=True, exist_ok=True)

    shared = _shared_codex_home(env)
    _symlink_or_copy_file(shared / "auth.json", home / "auth.json")
    _symlink_dir(shared / "sessions", home / "sessions")
    for name in ("config.json", "config.toml", "instructions.md"):
        src = shared / name
        if src.exists():
            shutil.copy2(src, home / name)
    config_path = home / "config.toml"
    if not config_path.exists():
        config_path.write_text("", encoding="utf-8")
    if mcp_toml:
        with config_path.open("a", encoding="utf-8") as handle:
            handle.write("\n")
            handle.write(mcp_toml)
        config_path.chmod(0o600)

    updated_env = dict(env)
    updated_env["CODEX_HOME"] = str(home)
    return updated_env, str(workspace_path)


def _remote_codex_home_lines(home_key: str, mcp_toml: str) -> list[str]:
    run_home = f".langbot-codex-home/{_safe_home_name(home_key)}"
    lines = [
        f"run_home={shlex.quote(run_home)}",
        'shared_home="${CODEX_HOME:-$HOME/.codex}"',
        'rm -rf "$run_home"',
        'mkdir -p "$run_home"',
        '[ -f "$shared_home/auth.json" ] && ln -s "$shared_home/auth.json" "$run_home/auth.json" || :',
        'mkdir -p "$shared_home/sessions"',
        'ln -s "$shared_home/sessions" "$run_home/sessions" 2>/dev/null || :',
        '[ -f "$shared_home/config.json" ] && cp "$shared_home/config.json" "$run_home/config.json" || :',
        '[ -f "$shared_home/config.toml" ] && cp "$shared_home/config.toml" "$run_home/config.toml" || :',
        '[ -f "$shared_home/instructions.md" ] && cp "$shared_home/instructions.md" "$run_home/instructions.md" || :',
        'touch "$run_home/config.toml"',
    ]
    if mcp_toml:
        encoded = base64.b64encode(("\n" + mcp_toml).encode("utf-8")).decode("ascii")
        lines.append(f"printf %s {shlex.quote(encoded)} | base64 -d >> \"$run_home/config.toml\"")
        lines.append('chmod 600 "$run_home/config.toml"')
    lines.append('export CODEX_HOME="$PWD/$run_home"')
    return lines


def _remote_shell_command(workspace: str, argv: list[str], env: dict[str, str], *, home_key: str, mcp_toml: str) -> str:
    lines = ["set -e"]
    lines.extend(f"export {shlex.quote(key)}={shlex.quote(value)}" for key, value in env.items())
    if workspace:
        quoted_workspace = shlex.quote(workspace)
        lines.append(f"mkdir -p {quoted_workspace}")
        lines.append(f"cd {quoted_workspace}")
    lines.extend(_remote_codex_home_lines(home_key, mcp_toml))
    lines.append(f"exec {shlex.join(argv)}")
    return f"bash -lc {shlex.quote(chr(10).join(lines))}"


def _input_text(ctx: AgentRunContext) -> str:
    return ctx.input.to_text().strip()


class NativeCodexRunner(AgentRunner):
    def _validate_config(self, ctx: AgentRunContext) -> dict[str, typing.Any]:
        data = ctx.config or {}
        location = str(data.get("location", "local") or "local").strip()
        if location not in SUPPORTED_LOCATIONS:
            raise NativeCliError("location must be local, remote-ssh, or daemon", code="codex.config_invalid")
        workspace = str(data.get("workspace") or "").strip() or os.getcwd()
        ssh_target = str(data.get("ssh-target") or data.get("ssh_target") or "").strip()
        if location == "remote-ssh" and not ssh_target:
            raise NativeCliError("ssh-target is required when location=remote-ssh", code="codex.config_invalid")
        daemon_id = str(data.get("daemon-id") or data.get("daemon_id") or "").strip()
        if location == "daemon" and not daemon_id:
            raise NativeCliError("daemon-id is required when location=daemon", code="codex.config_invalid")
        return {
            "location": location,
            "workspace": workspace,
            "command": str(data.get("command") or "codex"),
            "args": _parse_config_args(data.get("args-json") or data.get("args")),
            "env": {str(k): str(v) for k, v in _parse_json_object(data.get("env-json"), label="env-json").items()},
            "ssh_target": ssh_target,
            "ssh_port": _to_int(data.get("ssh-port"), 22),
            "daemon_id": daemon_id,
            "daemon_connect_timeout": _to_float(data.get("daemon-connect-timeout"), 30.0),
            "timeout": _to_float(data.get("timeout"), 300.0),
            "streaming": _to_bool(data.get("streaming"), True),
            "reuse_session": _to_bool(data.get("reuse-session"), True),
            "langbot_assets_enabled": _to_bool(data.get("langbot-assets-enabled"), True),
            "mcp_bridge_transport": str(data.get("mcp-bridge-transport", "auto") or "auto").strip(),
            "mcp_servers": _parse_json_list(data.get("mcp-servers-json"), label="mcp-servers-json"),
            "daemon_hub": agent_runtime_daemon_config_from_plugin_config(
                self.get_plugin_config(),
                env_prefix="LANGBOT_CODEX_DAEMON",
                default_port=8768,
            ),
        }

    def _stored_session_id(self, ctx: AgentRunContext) -> str:
        return str(ctx.state.conversation.get(SESSION_STATE_KEY) or "").strip()

    def _resume_session_id(self, ctx: AgentRunContext, config: dict[str, typing.Any]) -> str:
        stored = self._stored_session_id(ctx)
        if stored and config["reuse_session"]:
            return stored
        return ""

    def _argv(self, config: dict[str, typing.Any]) -> list[str]:
        return [*_parse_args(config["command"]), "app-server", "--listen", "stdio://", *config["args"]]

    def _mcp_access(self, ctx: AgentRunContext, config: dict[str, typing.Any]) -> AgentRunMCPAccess | None:
        if not config["langbot_assets_enabled"]:
            return None
        access = AgentRunMCPAccess(
            self.get_run_api(ctx),
            ctx,
            enabled=True,
            location=config["location"],
            mode="ephemeral",
            transport=config["mcp_bridge_transport"],
            bridge_request_timeout=config["timeout"],
        )
        access.start()
        return access

    async def run(self, ctx: AgentRunContext) -> typing.AsyncGenerator[AgentRunResult, None]:
        try:
            config = self._validate_config(ctx)
            prompt = _input_text(ctx)
            if not prompt:
                raise NativeCliError("input text is required", code="codex.empty_input")
            if config["location"] == "daemon":
                async for result in self._run_daemon(ctx, config, prompt):
                    yield result
                return
            async for result in self._run_local_or_ssh(ctx, config, prompt, self._resume_session_id(ctx, config)):
                yield result
        except NativeCliError as exc:
            yield AgentRunResult.run_failed(ctx.run_id, error=exc.message, code=exc.code, retryable=exc.retryable)
        except AgentRuntimeDaemonError as exc:
            yield AgentRunResult.run_failed(ctx.run_id, error=exc.message, code=exc.code, retryable=exc.retryable)

    async def _run_local_or_ssh(
        self,
        ctx: AgentRunContext,
        config: dict[str, typing.Any],
        prompt: str,
        session_id: str,
    ) -> typing.AsyncGenerator[AgentRunResult, None]:
        access = self._mcp_access(ctx, config)
        try:
            mcp_servers = _mcp_servers_config([access.server_config] if access and access.server_config else [], config["mcp_servers"])
            mcp_toml = _mcp_config_toml(mcp_servers)
            argv = self._argv(config)
            env = {**os.environ, **config["env"]}
            command = argv[0]
            args = argv[1:]
            cwd = config["workspace"] if config["location"] == "local" else None
            if config["location"] == "remote-ssh":
                ssh_args = ["-T", "-p", str(config["ssh_port"])]
                if access and access.reverse_tunnel:
                    ssh_args.extend(access.reverse_tunnel.ssh_args())
                ssh_args.extend(
                    [
                        config["ssh_target"],
                        _remote_shell_command(
                            config["workspace"],
                            argv,
                            config["env"],
                            home_key=session_id or ctx.run_id,
                            mcp_toml=mcp_toml,
                        ),
                    ]
                )
                command = "ssh"
                args = ssh_args
            else:
                env, cwd = _prepare_local_codex_home(config["workspace"], session_id or ctx.run_id, env, mcp_toml)
            async for result in _run_cli_process(
                ctx,
                command,
                args,
                cwd=cwd,
                env=env,
                timeout=config["timeout"],
                streaming=config["streaming"],
                resume_session_id=session_id,
                prompt=prompt,
                agent_cwd=config["workspace"],
            ):
                yield result
        finally:
            if access is not None:
                access.stop()

    async def _run_daemon(
        self,
        ctx: AgentRunContext,
        config: dict[str, typing.Any],
        prompt: str,
    ) -> typing.AsyncGenerator[AgentRunResult, None]:
        hub = get_agent_runtime_daemon_hub("codex", error_code_prefix="codex")
        if not hub.is_running:
            await hub.start(
                host=config["daemon_hub"]["host"],
                port=config["daemon_hub"]["port"],
                token=config["daemon_hub"]["token"],
            )
        session_id = self._resume_session_id(ctx, config)
        tools = AgentRunExternalTools(self.get_run_api(ctx), ctx) if config["langbot_assets_enabled"] else None
        await hub.wait_for_daemon(config["daemon_id"], config["daemon_connect_timeout"])
        payload = {
            "prompt": prompt,
            "session_id": session_id,
            "run_id": ctx.run_id,
            "config": {
                "command": config["command"],
                "args": config["args"],
                "workspace": config["workspace"],
                "env": config["env"],
                "timeout": config["timeout"],
                "streaming": config["streaming"],
                "mcp_servers": config["mcp_servers"],
                "langbot_assets_enabled": config["langbot_assets_enabled"],
            },
        }
        async for event in hub.run_job(
            daemon_id=config["daemon_id"],
            payload=payload,
            tools=tools,
            timeout=config["timeout"],
        ):
            event.setdefault("run_id", ctx.run_id)
            yield AgentRunResult.model_validate(event)


class NativeCodexDaemon(AgentRuntimeDaemonClient):
    async def run_job(self, job_id: str, payload: dict[str, typing.Any]) -> None:
        proxy = None
        config = payload.get("config") if isinstance(payload.get("config"), dict) else {}
        try:
            mcp_servers: list[AgentMCPServerConfig] = []
            if config.get("langbot_assets_enabled", True):
                proxy = self.create_mcp_proxy(job_id, request_timeout=float(config.get("timeout") or 300.0))
                proxy.start()
                mcp_servers.append(proxy.mcp_server())
            mcp_toml = _mcp_config_toml(_mcp_servers_config(mcp_servers, list(config.get("mcp_servers") or [])))
            argv = [*_parse_args(config.get("command") or "codex"), "app-server", "--listen", "stdio://", *list(config.get("args") or [])]
            session_id = str(payload.get("session_id") or "")
            env = {**os.environ, **{str(k): str(v) for k, v in dict(config.get("env") or {}).items()}}
            env, cwd = _prepare_local_codex_home(
                str(config.get("workspace") or os.getcwd()),
                session_id or str(payload.get("run_id") or job_id),
                env,
                mcp_toml,
            )
            async for event in _run_cli_process_events(
                argv[0],
                argv[1:],
                cwd=cwd,
                env=env,
                timeout=float(config.get("timeout") or 300.0),
                streaming=bool(config.get("streaming", True)),
                resume_session_id=session_id,
                prompt=str(payload.get("prompt") or ""),
                agent_cwd=cwd,
            ):
                await self.emit_event(job_id, event)
        finally:
            if proxy is not None:
                proxy.stop()


async def _run_cli_process(
    ctx: AgentRunContext,
    command: str,
    args: list[str],
    *,
    cwd: str | None,
    env: dict[str, str],
    timeout: float,
    streaming: bool,
    resume_session_id: str,
    prompt: str,
    agent_cwd: str,
) -> typing.AsyncGenerator[AgentRunResult, None]:
    async for event in _run_cli_process_events(
        command,
        args,
        cwd=cwd,
        env=env,
        timeout=timeout,
        streaming=streaming,
        resume_session_id=resume_session_id,
        prompt=prompt,
        agent_cwd=agent_cwd,
    ):
        event.setdefault("run_id", ctx.run_id)
        yield AgentRunResult.model_validate(event)


def _extract_nested_string(data: dict[str, typing.Any], *keys: str) -> str:
    current: typing.Any = data
    for key in keys:
        if not isinstance(current, dict):
            return ""
        current = current.get(key)
    return str(current) if isinstance(current, str) else ""


def _extract_thread_id(result: typing.Any) -> str:
    if not isinstance(result, dict):
        return ""
    for key in ("threadId", "thread_id", "id"):
        value = result.get(key)
        if isinstance(value, str) and value:
            return value
    thread = result.get("thread")
    if isinstance(thread, dict):
        for key in ("id", "threadId", "thread_id"):
            value = thread.get(key)
            if isinstance(value, str) and value:
                return value
    return ""


class _CodexAppServerClient:
    def __init__(self, process: asyncio.subprocess.Process, *, streaming: bool) -> None:
        self.process = process
        self.streaming = streaming
        self.next_id = 0
        self.pending: dict[int, asyncio.Future[typing.Any]] = {}
        self.events: asyncio.Queue[dict[str, typing.Any]] = asyncio.Queue()
        self.turn_done: asyncio.Future[None] = asyncio.get_running_loop().create_future()
        self.thread_id = ""
        self.turn_started = False
        self.sequence = 0
        self.final_parts: list[str] = []
        self.final_error = ""
        self.seen_agent_message_item_ids: set[str] = set()
        self.final_chunk_emitted = False

    async def _write_json(self, payload: dict[str, typing.Any]) -> None:
        assert self.process.stdin is not None
        data = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode("utf-8") + b"\n"
        self.process.stdin.write(data)
        await self.process.stdin.drain()

    async def request(self, method: str, params: dict[str, typing.Any] | None = None) -> typing.Any:
        self.next_id += 1
        request_id = self.next_id
        future: asyncio.Future[typing.Any] = asyncio.get_running_loop().create_future()
        self.pending[request_id] = future
        await self._write_json({"jsonrpc": "2.0", "id": request_id, "method": method, "params": params or {}})
        return await future

    async def notify(self, method: str) -> None:
        await self._write_json({"jsonrpc": "2.0", "method": method})

    async def respond(self, request_id: typing.Any, result: typing.Any) -> None:
        await self._write_json({"jsonrpc": "2.0", "id": request_id, "result": result})

    async def respond_error(self, request_id: typing.Any, message: str) -> None:
        await self._write_json({"jsonrpc": "2.0", "id": request_id, "error": {"code": -32601, "message": message}})

    async def initialize(self) -> None:
        await self.request(
            "initialize",
            {
                "clientInfo": {
                    "name": "langbot-codex-agent",
                    "title": "LangBot Codex Agent",
                "version": "0.1.7",
                },
                "capabilities": {"experimentalApi": True},
            },
        )
        await self.notify("initialized")

    async def start_or_resume_thread(self, resume_session_id: str, cwd: str) -> str:
        if resume_session_id:
            try:
                result = await self.request(
                    "thread/resume",
                    {
                        "threadId": resume_session_id,
                        "cwd": cwd,
                        "model": None,
                        "developerInstructions": None,
                    },
                )
                thread_id = _extract_thread_id(result)
                if thread_id:
                    self.thread_id = thread_id
                    return thread_id
            except Exception:
                pass

        result = await self.request(
            "thread/start",
            {
                "model": None,
                "modelProvider": None,
                "profile": None,
                "cwd": cwd,
                "approvalPolicy": None,
                "sandbox": None,
                "config": None,
                "baseInstructions": None,
                "developerInstructions": None,
                "compactPrompt": None,
                "includeApplyPatchTool": None,
                "experimentalRawEvents": False,
                "persistExtendedHistory": True,
            },
        )
        thread_id = _extract_thread_id(result)
        if not thread_id:
            raise NativeCliError("Codex thread/start returned no thread ID", code="codex.thread_start_failed")
        self.thread_id = thread_id
        return thread_id

    async def start_turn(self, thread_id: str, prompt: str) -> None:
        await self.request("turn/start", {"threadId": thread_id, "input": [{"type": "text", "text": prompt}]})

    async def read_stdout(self) -> None:
        assert self.process.stdout is not None
        try:
            while True:
                line = await self.process.stdout.readline()
                if not line:
                    break
                text = line.decode("utf-8", errors="replace").strip()
                if text:
                    await self.handle_line(text)
        finally:
            error = NativeCliError("Codex app-server exited before completing the turn", code="codex.process_exited")
            for request_id, future in list(self.pending.items()):
                if not future.done():
                    future.set_exception(error)
                self.pending.pop(request_id, None)
            if self.turn_started and not self.turn_done.done():
                self.turn_done.set_exception(error)

    async def handle_line(self, line: str) -> None:
        try:
            raw = json.loads(line)
        except json.JSONDecodeError:
            return
        if not isinstance(raw, dict):
            return
        if "id" in raw and ("result" in raw or "error" in raw):
            self.handle_response(raw)
            return
        if "id" in raw and "method" in raw:
            await self.handle_server_request(raw)
            return
        if "method" in raw:
            await self.handle_notification(raw)

    def handle_response(self, raw: dict[str, typing.Any]) -> None:
        request_id = raw.get("id")
        future = self.pending.pop(request_id, None) if isinstance(request_id, int) else None
        if future is None or future.done():
            return
        if "error" in raw:
            error = raw.get("error")
            if isinstance(error, dict):
                message = str(error.get("message") or error)
            else:
                message = str(error)
            future.set_exception(NativeCliError(message, code="codex.rpc_error"))
            return
        future.set_result(raw.get("result"))

    async def handle_server_request(self, raw: dict[str, typing.Any]) -> None:
        request_id = raw.get("id")
        method = str(raw.get("method") or "")
        if method in {"item/commandExecution/requestApproval", "execCommandApproval", "item/fileChange/requestApproval", "applyPatchApproval"}:
            await self.respond(request_id, {"decision": "accept"})
        elif method == "mcpServer/elicitation/request":
            await self.respond(request_id, {"action": "accept", "content": None, "_meta": None})
        else:
            await self.respond_error(request_id, f"unhandled server request: {method}")

    async def handle_notification(self, raw: dict[str, typing.Any]) -> None:
        method = str(raw.get("method") or "")
        params = raw.get("params")
        if not isinstance(params, dict):
            params = {}
        if method == "codex/event" or method.startswith("codex/event/"):
            msg = params.get("msg")
            if isinstance(msg, dict):
                await self.handle_legacy_event(msg)
            return
        if self.thread_id:
            event_thread_id = params.get("threadId")
            if isinstance(event_thread_id, str) and event_thread_id != self.thread_id:
                return
        await self.handle_raw_notification(method, params)

    async def handle_legacy_event(self, msg: dict[str, typing.Any]) -> None:
        msg_type = str(msg.get("type") or "")
        if msg_type == "task_started":
            self.turn_started = True
        elif msg_type == "agent_message":
            text = msg.get("message")
            if isinstance(text, str) and text:
                await self.emit_text(text)
        elif msg_type == "task_complete":
            self.finish_turn()
        elif msg_type == "turn_aborted":
            self.finish_turn(error="turn was aborted")

    async def handle_raw_notification(self, method: str, params: dict[str, typing.Any]) -> None:
        if method == "turn/started":
            self.turn_started = True
            return
        if method == "turn/completed":
            status = _extract_nested_string(params, "turn", "status")
            if status == "failed":
                self.finish_turn(error=_extract_nested_string(params, "turn", "error", "message") or "codex turn failed")
            else:
                self.finish_turn()
            return
        if method == "thread/status/changed" and self.turn_started:
            if _extract_nested_string(params, "status", "type") == "idle":
                self.finish_turn()
            return
        if method == "error":
            will_retry = bool(params.get("willRetry"))
            message = _extract_nested_string(params, "error", "message") or _extract_nested_string(params, "message")
            if message and not will_retry:
                self.finish_turn(error=message)
            return
        if method.startswith("item/"):
            await self.handle_item_notification(method, params)

    async def handle_item_notification(self, method: str, params: dict[str, typing.Any]) -> None:
        item = params.get("item")
        if not isinstance(item, dict):
            return
        item_type = str(item.get("type") or "")
        if method == "item/completed" and item_type == "agentMessage":
            item_id = str(item.get("id") or "")
            if item_id and item_id in self.seen_agent_message_item_ids:
                return
            if item_id:
                self.seen_agent_message_item_ids.add(item_id)
            text = item.get("text")
            is_final = item.get("phase") == "final_answer"
            if isinstance(text, str) and text:
                await self.emit_text(text, is_final=is_final)
            if is_final and self.turn_started:
                self.finish_turn()

    async def emit_text(self, text: str, *, is_final: bool = False) -> None:
        if is_final and self.final_chunk_emitted:
            return
        duplicate = bool(self.final_parts and self.final_parts[-1] == text)
        if duplicate and not is_final:
            return
        if not duplicate:
            self.final_parts.append(text)
        if not self.streaming:
            return
        all_content = "".join(self.final_parts)
        self.sequence += 1
        chunk = {
            "role": "assistant",
            "content": all_content if is_final else text,
            "all_content": all_content,
            "msg_sequence": self.sequence,
        }
        if is_final:
            chunk["is_final"] = True
            self.final_chunk_emitted = True
        await self.events.put(
            {
                "type": "message.delta",
                "sequence": self.sequence,
                "data": {"chunk": chunk},
            }
        )

    def finish_turn(self, error: str = "") -> None:
        if error and not self.final_error:
            self.final_error = error
        if not self.turn_done.done():
            if error:
                self.turn_done.set_exception(NativeCliError(error, code="codex.turn_failed"))
            else:
                self.turn_done.set_result(None)

    async def drain_events_until_done(self) -> typing.AsyncGenerator[dict[str, typing.Any], None]:
        while True:
            if self.turn_done.done():
                while not self.events.empty():
                    yield await self.events.get()
                await self.turn_done
                return
            get_task = asyncio.create_task(self.events.get())
            done, _ = await asyncio.wait({get_task, self.turn_done}, return_when=asyncio.FIRST_COMPLETED)
            if get_task in done:
                yield get_task.result()
            else:
                get_task.cancel()
                with contextlib.suppress(asyncio.CancelledError):
                    await get_task


async def _run_cli_process_events(
    command: str,
    args: list[str],
    *,
    cwd: str | None,
    env: dict[str, str],
    timeout: float,
    streaming: bool,
    resume_session_id: str,
    prompt: str,
    agent_cwd: str,
) -> typing.AsyncGenerator[dict[str, typing.Any], None]:
    process = await asyncio.create_subprocess_exec(
        command,
        *args,
        cwd=cwd,
        env=env,
        stdin=asyncio.subprocess.PIPE,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    assert process.stdout is not None
    assert process.stdin is not None
    assert process.stderr is not None
    client = _CodexAppServerClient(process, streaming=streaming)
    reader_task = asyncio.create_task(client.read_stdout())
    stderr_task = asyncio.create_task(process.stderr.read())
    result_sequence = 0
    try:
        async with asyncio.timeout(timeout):
            await client.initialize()
            thread_id = await client.start_or_resume_thread(resume_session_id, agent_cwd)
            if thread_id and thread_id != resume_session_id:
                result_sequence += 1
                yield {
                    "type": "state.updated",
                    "sequence": result_sequence,
                    "data": {"key": SESSION_STATE_KEY, "value": thread_id, "scope": "conversation"},
                }
            await client.start_turn(thread_id, prompt)
            async for event in client.drain_events_until_done():
                result_sequence += 1
                event["sequence"] = result_sequence
                yield event
        await _shutdown_app_server(process, reader_task)
        stderr = (await stderr_task).decode("utf-8", errors="replace").strip()
        if process.returncode not in (0, None):
            raise NativeCliError(stderr or f"Codex app-server exited with status {process.returncode}", code="codex.process_failed")
        if client.final_error:
            raise NativeCliError(client.final_error, code="codex.turn_failed")
        final_text = "".join(client.final_parts).strip()
        if not final_text:
            raise NativeCliError("Codex returned no assistant text", code="codex.empty_response")
        if streaming:
            if not client.final_chunk_emitted:
                client.sequence += 1
                result_sequence += 1
                yield {
                    "type": "message.delta",
                    "sequence": result_sequence,
                    "data": {
                        "chunk": {
                            "role": "assistant",
                            "content": final_text,
                            "all_content": final_text,
                            "is_final": True,
                            "msg_sequence": client.sequence,
                        }
                    },
                }
        else:
            result_sequence += 1
            yield {
                "type": "message.completed",
                "sequence": result_sequence,
                "data": {"message": {"role": "assistant", "content": final_text}},
            }
        result_sequence += 1
        yield {"type": "run.completed", "sequence": result_sequence, "data": {"finish_reason": "stop"}}
    except TimeoutError as exc:
        process.kill()
        raise NativeCliError("Codex app-server run timed out", code="codex.timeout", retryable=True) from exc
    finally:
        if process.returncode is None:
            process.kill()
        if not stderr_task.done():
            stderr_task.cancel()
        if not reader_task.done():
            reader_task.cancel()


async def _shutdown_app_server(process: asyncio.subprocess.Process, reader_task: asyncio.Task[None]) -> None:
    if process.stdin and not process.stdin.is_closing():
        process.stdin.close()
        try:
            await process.stdin.wait_closed()
        except (BrokenPipeError, ConnectionResetError):
            pass
    try:
        await asyncio.wait_for(process.wait(), timeout=10)
    except TimeoutError:
        process.kill()
        await process.wait()
    with contextlib.suppress(asyncio.CancelledError):
        await reader_task
